export const DATOS_SECTORES = [
  { nombre: "Aula 1A", interno: "14278", ubicacionId: 1 },
  { nombre: "Aula 1B", interno: "14277", ubicacionId: 1 },
  { nombre: "Aula Magna 1º piso", interno: "14240", ubicacionId: 1 },
  { nombre: "Aula Magna 2º piso", interno: "14311", ubicacionId: 1 },
  { nombre: "BioAc - Limpieza", interno: "14225", ubicacionId: 1 },
  { nombre: "Bioingenieria", interno: "14206", ubicacionId: 1 },
  { nombre: "Central Aires Acondicionados", interno: "14320", ubicacionId: 1 },
  { nombre: "Comedor", interno: "14266", ubicacionId: 1 },
  { nombre: "Comision Ejecutiva", interno: "14316", ubicacionId: 1 },
  { nombre: "Comision Ejecutiva Secretaria", interno: "14312", ubicacionId: 1 },
  { nombre: "Compras 1", interno: "14292", ubicacionId: 1 },
  { nombre: "Compras 2", interno: "14293", ubicacionId: 1 },
  { nombre: "Contable", interno: "14261", ubicacionId: 1 },
  { nombre: "Cuidados Progresivos 1-1", interno: "14251", ubicacionId: 1 },
  { nombre: "Cuidados Progresivos 1-2", interno: "14260", ubicacionId: 1 },
  { nombre: "Cuidados Progresivos 1-3", interno: "14267", ubicacionId: 1 },
  { nombre: "Direccion", interno: "14314", ubicacionId: 1 },
  { nombre: "Cuidados Progresivos 2", interno: "14268", ubicacionId: 1 },
  { nombre: "Direccion - Secretaria", interno: "14318", ubicacionId: 1 },
  { nombre: "Enfermeria Supervision 1", interno: "14280", ubicacionId: 1 },
  { nombre: "Enfermeria Supervision 2", interno: "14217", ubicacionId: 1 },
  { nombre: "Estadistica 1", interno: "14287", ubicacionId: 1 },
  { nombre: "Estadistica 2", interno: "14285", ubicacionId: 1 },
  { nombre: "Estadistica - Archivo", interno: "14265", ubicacionId: 1 },
  { nombre: "Esterelizacion", interno: "14322", ubicacionId: 1 },
  { nombre: "Facturacion 1", interno: "14308", ubicacionId: 1 },
  { nombre: "Facturacion 2", interno: "14309", ubicacionId: 1 },
  { nombre: "Farmacia - Dispensa Medicamentos", interno: "14263", ubicacionId: 1 },
  { nombre: "Farmacia - Esterelizacion", interno: "14226", ubicacionId: 1 },
  { nombre: "Farmacia Deposito 1", interno: "14302", ubicacionId: 1 },
  { nombre: "Farmacia Deposito 2", interno: "14303", ubicacionId: 1 },
  { nombre: "Farmacia Deposito 3", interno: "14295", ubicacionId: 1 },
  { nombre: "Farmacia Deposito Jefatura", interno: "14304", ubicacionId: 1 },
  { nombre: "Guardia - Admision 1", interno: "14296", ubicacionId: 1 },
  { nombre: "Guardia - Admision 2", interno: "14209", ubicacionId: 1 },
  { nombre: "Guardia - Admision Ambulancia", interno: "14269", ubicacionId: 1 },
  { nombre: "Guardia - Enfermeria", interno: "14218", ubicacionId: 1 },
  { nombre: "Guardia - Office Enfermeria 1", interno: "14222", ubicacionId: 1 },
  { nombre: "Guardia - Office Enfermeria 2", interno: "14223", ubicacionId: 1 },
  { nombre: "Guardia - Shock Room", interno: "14219", ubicacionId: 1 },
  { nombre: "Guardia Consultorio 1", interno: "14201", ubicacionId: 1 },
  { nombre: "Guardia Consultorio 2", interno: "14213", ubicacionId: 1 },
  { nombre: "Guardia Consultorio 3", interno: "14214", ubicacionId: 1 },
  { nombre: "Guardia Consultorio 4", interno: "14215", ubicacionId: 1 },
  { nombre: "Guardia Triage Adulto", interno: "14298", ubicacionId: 1 },
  { nombre: "Guardia Triage Pediatrico", interno: "14297", ubicacionId: 1 },
  { nombre: "Hemoterapia", interno: "14294", ubicacionId: 1 },
  { nombre: "Hemoterapia - Admision", interno: "14286", ubicacionId: 1 },
  { nombre: "Hemoterapia - Procesamiento ", interno: "14301", ubicacionId: 1 },
  { nombre: "Informatica", interno: "14224", ubicacionId: 1 },
  { nombre: "Internacion Conjunta Office 1", interno: "14276", ubicacionId: 1 },
  { nombre: "Internacion Conjunta Office 2", interno: "14237", ubicacionId: 1 },
  { nombre: "Laboratorio 1", interno: "14282", ubicacionId: 1 },
  { nombre: "Laboratorio 2", interno: "14283", ubicacionId: 1 },
  { nombre: "Laboratorio 3", interno: "14284", ubicacionId: 1 },
  { nombre: "Laboratorio - Microbiologia", interno: "14281", ubicacionId: 1 },
  { nombre: "Laboratorio - Preanalitica", interno: "14245", ubicacionId: 1 },
  { nombre: "Lavadero", interno: "14323", ubicacionId: 1 },
  { nombre: "Legales", interno: "14313", ubicacionId: 1 },
  { nombre: "Mantenimiento", interno: "14228", ubicacionId: 1 },
  { nombre: "Neonatologia Estar Medico", interno: "14252", ubicacionId: 1 },
  { nombre: "Neonatologia Habitacion Med", interno: "14275", ubicacionId: 1 },
  { nombre: "Neonatologia Jefa Enfermeria", interno: "14274", ubicacionId: 1 },
  { nombre: "Neonatologia Lactario", interno: "14254", ubicacionId: 1 },
  { nombre: "Neonatologia Office Enfermeria", interno: "14253", ubicacionId: 1 },
  { nombre: "Nutricion", interno: "14262", ubicacionId: 1 },
  { nombre: "Pediatria Estar Personal", interno: "14259", ubicacionId: 1 },
  { nombre: "Pediatria Internacion Office Enf. 1", interno: "14258", ubicacionId: 1 },
  { nombre: "Pediatria Internacion Office Enf. 2", interno: "14257", ubicacionId: 1 },
  { nombre: "Pediatria Internacion Office Enf. 3", interno: "14250", ubicacionId: 1 },
  { nombre: "Patologia", interno: "14338", ubicacionId: 1 },
  { nombre: "Quimioterapia", interno: "14289", ubicacionId: 1 },
  { nombre: "Quirofano Estar Medico", interno: "14234", ubicacionId: 1 },
  { nombre: "Quirofano Office Enfermeria", interno: "14230", ubicacionId: 1 },
  { nombre: "Rayos Admision", interno: "14212", ubicacionId: 1 },
  { nombre: "Rayos Consola Tomografo", interno: "14211", ubicacionId: 1 },
  { nombre: "Rayos Sala de Comandos", interno: "14216", ubicacionId: 1 },
  { nombre: "Registro Civil ", interno: "14239", ubicacionId: 1 },
  { nombre: "RRHH 1", interno: "14321", ubicacionId: 1 },
  { nombre: "RRHH 2", interno: "14291", ubicacionId: 1 },
  { nombre: "RRHH 3", interno: "14210", ubicacionId: 1 },
  { nombre: "RRHH Jefatura", interno: "14317", ubicacionId: 1 },
  { nombre: "RRHH - Admision Ventanilla", interno: "14299", ubicacionId: 1 },
  { nombre: "Sala Medicos Clinicos", interno: "14270", ubicacionId: 1 },
  { nombre: "Sala Medicos Pediatricos", interno: "14271", ubicacionId: 1 },
  { nombre: "Sala Reuniones D-1", interno: "14256", ubicacionId: 1 },
  { nombre: "Servicio Gral. Mucamas", interno: "14264", ubicacionId: 1 },
  { nombre: "Servicio Social", interno: "14232", ubicacionId: 1 },
  { nombre: "Tesoreria 1", interno: "14306", ubicacionId: 1 },
  { nombre: "Tesoreria 2", interno: "14305", ubicacionId: 1 },
  { nombre: "UCIP", interno: "14244", ubicacionId: 1 },
  { nombre: "UTI Adulto 1", interno: "14243", ubicacionId: 1 },
  { nombre: "UTI Adulto 2", interno: "14247", ubicacionId: 1 },
  { nombre: "UTI Adulto - Estar Medico", interno: "14246", ubicacionId: 1 },
  { nombre: "UTI Informes Adulto", interno: "14249", ubicacionId: 1 },
  { nombre: "UTIP Informes ", interno: "14248", ubicacionId: 1 },
  { nombre: "UTPR Consultorio A", interno: "14236", ubicacionId: 1 },
  { nombre: "UTPR Consultorio B", interno: "14238", ubicacionId: 1 },
  { nombre: "UTPR Estar Medico", interno: "14242", ubicacionId: 1 },
  { nombre: "UTPR Jefa Enfermeria", interno: "14241", ubicacionId: 1 },
  { nombre: "UTPR Office Enfermeria", interno: "14237", ubicacionId: 1 },
  { nombre: "UTPR Quirofano", interno: "14235", ubicacionId: 1 },
  { nombre: "UTPR Sala Parto 1", interno: "14319", ubicacionId: 1 },
  { nombre: "UTPR Sala Parto 2", interno: "14233", ubicacionId: 1 },
  { nombre: "Vigilancia", interno: "14300", ubicacionId: 1 },
  { nombre: "UCO", interno: "14207", ubicacionId: 1 },


];