export const DATOS_SECTORES = [

  // HOSPITAL JAIME FERRÉ 
  
  { nombre: "Aula 1B", interno: ["14277"], ubicacionId: 1 },
  { nombre: "Aula Magna 1º piso", interno: ["14240"], ubicacionId: 1 },
  { nombre: "Aula Magna 2º piso", interno: ["14311"], ubicacionId: 1 },
  { nombre: "BioAc - Limpieza", interno: ["14225"], ubicacionId: 1 },
  { nombre: "Bioingenieria", interno: ["14206"], ubicacionId: 1 },
  { nombre: "Central Aires Acondicionados", interno: ["14320"], ubicacionId: 1 },
  { nombre: "Comedor", interno: ["14266"], ubicacionId: 1 },
  { nombre: "Comision Ejecutiva", interno: ["14316"], ubicacionId: 1 },
  { nombre: "Comision Ejecutiva Secretaria", interno: ["14312"], ubicacionId: 1 },
  { nombre: "Compras", interno: ["14292", "14293"], ubicacionId: 1 },
  { nombre: "Contable", interno: ["14261"], ubicacionId: 1 },
  { nombre: "Cuidados Progresivos 1", interno: ["14251", "14260"], ubicacionId: 1 },
  { nombre: "Cuidados Progresivos 2", interno: ["14267", "14268"], ubicacionId: 1 },
  { nombre: "Direccion", interno: ["14314"], ubicacionId: 1 },
  { nombre: "Direccion - Secretaria", interno: ["14318"], ubicacionId: 1 },
  { nombre: "Enfermeria Supervision", interno: ["14280", "14217"], ubicacionId: 1 },
  { nombre: "Estadistica", interno: ["14287", "14285"], ubicacionId: 1 },
  { nombre: "Estadistica - Archivo", interno: ["14265"], ubicacionId: 1 },
  { nombre: "Esterelizacion", interno: ["14322"], ubicacionId: 1 },
  { nombre: "Facturacion", interno: ["14308", "14309"], ubicacionId: 1 },
  { nombre: "Farmacia - Dispensa Medicamentos", interno: ["14263"], ubicacionId: 1 },
  { nombre: "Farmacia - Esterelizacion", interno: ["14226"], ubicacionId: 1 },
  { nombre: "Farmacia Deposito", interno: ["14302", "14303", "14295"], ubicacionId: 1 },
  { nombre: "Farmacia Deposito Jefatura", interno: ["14304"], ubicacionId: 1 },
  { nombre: "Guardia - Admision", interno: ["14296", "14209"], ubicacionId: 1 },
  { nombre: "Guardia - Admision Ambulancia", interno: ["14269"], ubicacionId: 1 },
  { nombre: "Guardia - Enfermeria", interno: ["14218"], ubicacionId: 1 },
  { nombre: "Guardia - Office Enfermeria", interno: ["14222", "14223"], ubicacionId: 1 },
  { nombre: "Guardia - Shock Room", interno: ["14219"], ubicacionId: 1 },
  { nombre: "Guardia Consultorio 1", interno: ["14201"], ubicacionId: 1 },
  { nombre: "Guardia Consultorio 2", interno: ["14213"], ubicacionId: 1 },
  { nombre: "Guardia Consultorio 3", interno: ["14214"], ubicacionId: 1 },
  { nombre: "Guardia Consultorio 4", interno: ["14215"], ubicacionId: 1 },
  { nombre: "Guardia Triage Adulto", interno: ["14298"], ubicacionId: 1 },
  { nombre: "Guardia Triage Pediatrico", interno: ["14297"], ubicacionId: 1 },
  { nombre: "Hemoterapia", interno: ["14294"], ubicacionId: 1 },
  { nombre: "Hemoterapia - Admision", interno: ["14286"], ubicacionId: 1 },
  { nombre: "Hemoterapia - Procesamiento", interno: ["14301"], ubicacionId: 1 },
  { nombre: "Informatica", interno: ["14224"], ubicacionId: 1 },
  { nombre: "Internacion Conjunta Office", interno: ["14276", "14237"], ubicacionId: 1 },
  { nombre: "Laboratorio", interno: ["14282", "14283", "14284"], ubicacionId: 1 },
  { nombre: "Laboratorio - Microbiologia", interno: ["14281"], ubicacionId: 1 },
  { nombre: "Laboratorio - Preanalitica", interno: ["14245"], ubicacionId: 1 },
  { nombre: "Lavadero", interno: ["14323"], ubicacionId: 1 },
  { nombre: "Legales", interno: ["14313"], ubicacionId: 1 },
  { nombre: "Mantenimiento", interno: ["14228"], ubicacionId: 1 },
  { nombre: "Neonatologia Estar Medico", interno: ["14252"], ubicacionId: 1 },
  { nombre: "Neonatologia Habitacion Med", interno: ["14275"], ubicacionId: 1 },
  { nombre: "Neonatologia Jefa Enfermeria", interno: ["14274"], ubicacionId: 1 },
  { nombre: "Neonatologia Lactario", interno: ["14254"], ubicacionId: 1 },
  { nombre: "Neonatologia Office Enfermeria", interno: ["14253"], ubicacionId: 1 },
  { nombre: "Nutricion", interno: ["14262"], ubicacionId: 1 },
  { nombre: "Pediatria Estar Personal", interno: ["14259"], ubicacionId: 1 },
  { nombre: "Pediatria Internacion Office Enf.", interno: ["14258", "14257", "14250"], ubicacionId: 1 },
  { nombre: "Patologia", interno: ["14338"], ubicacionId: 1 },
  { nombre: "Quimioterapia", interno: ["14289"], ubicacionId: 1 },
  { nombre: "Quirofano Estar Medico", interno: ["14234"], ubicacionId: 1 },
  { nombre: "Quirofano Office Enfermeria", interno: ["14230"], ubicacionId: 1 },
  { nombre: "Rayos Admision", interno: ["14212"], ubicacionId: 1 },
  { nombre: "Rayos Consola Tomografo", interno: ["14211"], ubicacionId: 1 },
  { nombre: "Rayos Sala de Comandos", interno: ["14216"], ubicacionId: 1 },
  { nombre: "Registro Civil", interno: ["14239"], ubicacionId: 1 },
  { nombre: "RRHH", interno: ["14321", "14291", "14210"], ubicacionId: 1 },
  { nombre: "RRHH Jefatura", interno: ["14317"], ubicacionId: 1 },
  { nombre: "RRHH - Admision Ventanilla", interno: ["14299"], ubicacionId: 1 },
  { nombre: "Sala Medicos Clinicos", interno: ["14270"], ubicacionId: 1 },
  { nombre: "Sala Medicos Pediatricos", interno: ["14271"], ubicacionId: 1 },
  { nombre: "Sala Reuniones D-1", interno: ["14256"], ubicacionId: 1 },
  { nombre: "Servicio Gral. Mucamas", interno: ["14264"], ubicacionId: 1 },
  { nombre: "Servicio Social", interno: ["14232"], ubicacionId: 1 },
  { nombre: "Tesoreria", interno: ["14306", "14305"], ubicacionId: 1 },
  { nombre: "UCIP", interno: ["14244"], ubicacionId: 1 },
  { nombre: "UTI Adulto", interno: ["14243", "14247"], ubicacionId: 1 },
  { nombre: "UTI Adulto - Estar Medico", interno: ["14246"], ubicacionId: 1 },
  { nombre: "UTI Informes Adulto", interno: ["14249"], ubicacionId: 1 },
  { nombre: "UTIP Informes", interno: ["14248"], ubicacionId: 1 },
  { nombre: "UTPR Consultorio A", interno: ["14236"], ubicacionId: 1 },
  { nombre: "UTPR Consultorio B", interno: ["14238"], ubicacionId: 1 },
  { nombre: "UTPR Estar Medico", interno: ["14242"], ubicacionId: 1 },
  { nombre: "UTPR Jefa Enfermeria", interno: ["14241"], ubicacionId: 1 },
  { nombre: "UTPR Office Enfermeria", interno: ["14237"], ubicacionId: 1 },
  { nombre: "UTPR Quirofano", interno: ["14235"], ubicacionId: 1 },
  { nombre: "UTPR Sala Parto 1", interno: ["14319"], ubicacionId: 1 },
  { nombre: "UTPR Sala Parto 2", interno: ["14233"], ubicacionId: 1 },
  { nombre: "Vigilancia", interno: ["14300"], ubicacionId: 1 },
  { nombre: "UCO", interno: ["14207"], ubicacionId: 1 },

  // ANEXO

  { nombre: "Informatica", interno: ["14324"], ubicacionId: 2 },
  { nombre: "Estadistica", interno: ["14325", "14326"], ubicacionId: 2 },
  { nombre: "Farmacia", interno: ["14327", "14328"], ubicacionId: 2 },
  { nombre: "Rayos", interno: ["14329"], ubicacionId: 2 },
  { nombre: "Seguridad", interno: ["14330"], ubicacionId: 2 },
  { nombre: "Caja", interno: ["14331"], ubicacionId: 2 },
  { nombre: "Admision", interno: ["14332"], ubicacionId: 2 },
  { nombre: "S. Social", interno: ["14333"], ubicacionId: 2 },
  { nombre: "Direccion", interno: ["14334"], ubicacionId: 2 },
  { nombre: "Deposito", interno: ["14335"], ubicacionId: 2 },
  { nombre: "Mantenimiento", interno: ["14336"], ubicacionId: 2 },
  { nombre: "107", interno: ["14337"], ubicacionId: 2 },
 // { nombre: "LIBRE - IP Libre", interno: [], ubicacionId: 2 },
  { nombre: "Rehabilitacion", interno: [14339], ubicacionId: 2 },
  { nombre: "Laboratorio", interno: ["14340"], ubicacionId: 2 },
  { nombre: "Personal", interno: ["14341"], ubicacionId: 2 },
  { nombre: "APS", interno: ["14342"], ubicacionId: 2 },
  { nombre: "Drogueria", interno: ["14343"], ubicacionId: 2 },
  { nombre: "Oncologia", interno: ["14344"], ubicacionId: 2 },
  { nombre: "Cirugia", interno: ["14345"], ubicacionId: 2 },
  { nombre: "Odontologia", interno: ["14346"], ubicacionId: 2 },
  { nombre: "Oftalmologia", interno: ["14347"], ubicacionId: 2 },
  { nombre: "Enfermeria", interno: ["14348"], ubicacionId: 2 },
  { nombre: "Vacunatorio", interno: ["14349"], ubicacionId: 2 },
  { nombre: "Salud Mental", interno: ["14350"], ubicacionId: 2 },
  { nombre: "Neurologia", interno: ["14362"], ubicacionId: 2 },
  { nombre: "Embarazo Alto Riesgo", interno: ["14363"], ubicacionId: 2 },
  { nombre: "Obstetricia", interno: ["14364"], ubicacionId: 2 },
  { nombre: "Pediatria", interno: ["14365", "14367"], ubicacionId: 2 },
  { nombre: "Endocrinologia", interno: ["14366"], ubicacionId: 2 },
  { nombre: "Cardiologia", interno: ["14368"], ubicacionId: 2 },
  { nombre: "Clinica Medica / Psicologia", interno: ["14369"], ubicacionId: 2 },
  { nombre: "Infectologia", interno: ["14370"], ubicacionId: 2 },
  { nombre: "Psicologia", interno: ["14371"], ubicacionId: 2 },
  { nombre: "Traumatologia", interno: ["14372"], ubicacionId: 2 },
  { nombre: "Nefrologia", interno: ["14373"], ubicacionId: 2 },
  { nombre: "Office Enfermeria", interno: ["14374"], ubicacionId: 2 },
  { nombre: "Admision Estadistica", interno: ["14375"], ubicacionId: 2 },
  { nombre: "Ginecologia", interno: ["14376"], ubicacionId: 2 },
  { nombre: "Psiquiatria", interno: ["14377"], ubicacionId: 2 },
  { nombre: "Otorrino", interno: ["14378"], ubicacionId: 2 },
  { nombre: "Certificados-Discapacidad", interno: ["14379"], ubicacionId: 2 },

  // CENTROS DE SALUD

  { nombre: "CS1", interno: ["14351"], ubicacionId: 3 },
  { nombre: "CS2", interno: ["14352"], ubicacionId: 4 },
  { nombre: "CS3", interno: ["14353"], ubicacionId: 5 },
  { nombre: "CS4", interno: ["14354"], ubicacionId: 6 },
  { nombre: "CS5", interno: ["14355"], ubicacionId: 7 },
  { nombre: "CS6", interno: ["14356"], ubicacionId: 8 },
  { nombre: "CS7", interno: ["13357"], ubicacionId: 9 },
  { nombre: "CS8", interno: ["14358"], ubicacionId: 10 },
  { nombre: "CS9", interno: ["14359"], ubicacionId: 11 },
  { nombre: "CS10", interno: ["14360"], ubicacionId: 12 },
  { nombre: "CS11", interno: ["14361"], ubicacionId: 13 },
];