export const DATOS_SECTORES = [
  { nombre: "Aula 1A", interno: "14278" },
  { nombre: "Aula 1B", interno: "14277" },
  { nombre: "Aula Magna 1º piso", interno: "14240" },
  { nombre: "Aula Magna 2º piso", interno: "14311" },
  { nombre: "BioAc - Limpieza", interno: "14225" },
  { nombre: "Bioingenieria", interno: "14206" },
  { nombre: "Central Aires Acondicionados", interno: "14320" },
  { nombre: "Comedor", interno: "14266" },
  { nombre: "Comision Ejecutiva", interno: "14316" },
  { nombre: "Comision Ejecutiva Secretaria", interno: "14312" },
  { nombre: "Compras 1", interno: "14292" },
  { nombre: "Compras 2", interno: "14293" },
  { nombre: "Contable", interno: "14261" },
  { nombre: "Cuidados Progresivos 1-1", interno: "14251" },
  { nombre: "Cuidados Progresivos 1-2", interno: "14260" },
  { nombre: "Cuidados Progresivos 1-3", interno: "14267" },
  { nombre: "Direccion", interno: "14314" },
  { nombre: "Cuidados Progresivos 2", interno: "14268" },
  { nombre: "Direccion - Secretaria", interno: "14318" },
  { nombre: "Enfermeria Supervision 1", interno: "14280" },
  { nombre: "Enfermeria Supervision 2", interno: "14217" },
  { nombre: "Estadistica 1", interno: "14287" },
  { nombre: "Estadistica 2", interno: "14285" },
  { nombre: "Estadistica - Archivo", interno: "14265" },
  { nombre: "Esterelizacion", interno: "14322" },
  { nombre: "Facturacion 1", interno: "14308" },
  { nombre: "Facturacion 2", interno: "14309" },
  { nombre: "Farmacia - Dispensa Medicamentos", interno: "14263" },
  { nombre: "Farmacia - Esterelizacion", interno: "14226" },
  { nombre: "Farmacia Deposito 1", interno: "14302" },
  { nombre: "Farmacia Deposito 2", interno: "14303" },
  { nombre: "Farmacia Deposito 3", interno: "14295" },
  { nombre: "Farmacia Deposito Jefatura", interno: "14304" },
  { nombre: "Guardia - Admision 1", interno: "14296" },
  { nombre: "Guardia - Admision 2", interno: "14209" },
  { nombre: "Guardia - Admision Ambulancia", interno: "14269" },
  { nombre: "Guardia - Enfermeria", interno: "14218" },
  { nombre: "Guardia - Office Enfermeria 1", interno: "14222" },
  { nombre: "Guardia - Office Enfermeria 2", interno: "14223" },
  { nombre: "Guardia - Shock Room", interno: "14219" },
  { nombre: "Guardia Consultorio 1", interno: "14201" },
  { nombre: "Guardia Consultorio 2", interno: "14213" },
  { nombre: "Guardia Consultorio 3", interno: "14214" },
  { nombre: "Guardia Consultorio 4", interno: "14215" },
  { nombre: "Guardia Triage Adulto", interno: "14298" },
  { nombre: "Guardia Triage Pediatrico", interno: "14297" },
  { nombre: "Hemoterapia", interno: "14294" },
  { nombre: "Hemoterapia - Admision", interno: "14286" },
  { nombre: "Hemoterapia - Procesamiento ", interno: "14301" },
  { nombre: "Informatica", interno: "14224" },
  { nombre: "Internacion Conjunta Office 1", interno: "14276" },
  { nombre: "Internacion Conjunta Office 2", interno: "14237" },
  { nombre: "Laboratorio 1", interno: "14282" },
  { nombre: "Laboratorio 2", interno: "14283" },
  { nombre: "Laboratorio 3", interno: "14284" },
  { nombre: "Laboratorio - Microbiologia", interno: "14281" },
  { nombre: "Laboratorio - Preanalitica", interno: "14245" },
  { nombre: "Lavadero", interno: "14323" },
  { nombre: "Legales", interno: "14313" },
  { nombre: "Mantenimiento", interno: "14228" },
  { nombre: "Neonatologia Estar Medico", interno: "14252" },
  { nombre: "Neonatologia Habitacion Med", interno: "14275" },
  { nombre: "Neonatologia Jefa Enfermeria", interno: "14274" },
  { nombre: "Neonatologia Lactario", interno: "14254" },
  { nombre: "Neonatologia Office Enfermeria", interno: "14253" },
  { nombre: "Nutricion", interno: "14262" },
  { nombre: "Pediatria Estar Personal", interno: "14259" },
  { nombre: "Pediatria Internacion Office Enf. 1", interno: "14258" },
  { nombre: "Pediatria Internacion Office Enf. 2", interno: "14257" },
  { nombre: "Pediatria Internacion Office Enf. 3", interno: "14250" },
  { nombre: "Patologia", interno: "14338" },
  { nombre: "Quimioterapia", interno: "14289" },
  { nombre: "Quirofano Estar Medico", interno: "14234" },
  { nombre: "Quirofano Office Enfermeria", interno: "14230" },
  { nombre: "Rayos Admision", interno: "14212" },
  { nombre: "Rayos Consola Tomografo", interno: "14211" },
  { nombre: "Rayos Sala de Comandos", interno: "14216" },
  { nombre: "Registro Civil ", interno: "14239" },
  { nombre: "RRHH 1", interno: "14321" },
  { nombre: "RRHH 2", interno: "14291" },
  { nombre: "RRHH 3", interno: "14210" },
  { nombre: "RRHH Jefatura", interno: "14317" },
  { nombre: "RRHH - Admision Ventanilla", interno: "14299" },
  { nombre: "Sala Medicos Clinicos", interno: "14270" },
  { nombre: "Sala Medicos Pediatricos", interno: "14271" },
  { nombre: "Sala Reuniones D-1", interno: "14256" },
  { nombre: "Servicio Gral. Mucamas", interno: "14264" },
  { nombre: "Servicio Social", interno: "14232" },
  { nombre: "Tesoreria 1", interno: "14306" },
  { nombre: "Tesoreria 2", interno: "14305" },
  { nombre: "UCIP", interno: "14244" },
  { nombre: "UTI Adulto 1", interno: "14243" },
  { nombre: "UTI Adulto 2", interno: "14247" },
  { nombre: "UTI Adulto - Estar Medico", interno: "14246" },
  { nombre: "UTI Informes Adulto", interno: "14249" },
  { nombre: "UTIP Informes ", interno: "14248" },
  { nombre: "UTPR Consultorio A", interno: "14236" },
  { nombre: "UTPR Consultorio B", interno: "14238" },
  { nombre: "UTPR Estar Medico", interno: "14242" },
  { nombre: "UTPR Jefa Enfermeria", interno: "14241" },
  { nombre: "UTPR Office Enfermeria", interno: "14237" },
  { nombre: "UTPR Quirofano", interno: "14235" },
  { nombre: "UTPR Sala Parto 1", interno: "14319" },
  { nombre: "UTPR Sala Parto 2", interno: "14233" },
  { nombre: "Vigilancia", interno: "14300" },
  { nombre: "UCO", interno: "14207" },
];

