export const UBICACIONES = [
  { id: 1, nombre: "Hospital Dr. Jaime Ferré" },
  { id: 2, nombre: "Anexo Hospital Dr. Jaime Ferré" },
  { id: 3, nombre: "Centro de Salud 1" },
  { id: 4, nombre: "Centro de Salud 2" },
  { id: 5, nombre: "Centro de Salud 3" },
  { id: 6, nombre: "Centro de Salud 4" },
  { id: 7, nombre: "Centro de Salud 5" },
  { id: 8, nombre: "Centro de Salud 6" },
  { id: 9, nombre: "Centro de Salud 7" },
  { id: 10, nombre: "Centro de Salud 8" },
  { id: 11, nombre: "Centro de Salud 9" },
  { id: 12, nombre: "Centro de Salud 10" },
  { id: 13, nombre: "Centro de Salud 11" },
  { id: 14, nombre: "Ministerio de Salud" },
];